# Version
grafana_version: "8.2.2"

# System Users (created by package)
grafana_system_user: "grafana"
grafana_system_group: "grafana"

# Web Admin Users (from inventory/vault)
grafana_admin_user: "{{ grafana_user }}"
grafana_admin_password: "{{ grafana_admin_password }}"

# Network Configuration
grafana_port: 3000
grafana_domain: localhost
grafana_url: "http://{{ grafana_domain }}:{{ grafana_port }}"
grafana_protocol: "http"

# Prometheus Configuration
prometheus_port: 9090
prometheus_host: "localhost"
prometheus_url: "http://{{ prometheus_host }}:{{ prometheus_port }}"

# Security
grafana_allow_sign_up: false
grafana_allow_org_create: false
grafana_verify_ssl: false

# Paths
grafana_data_dir: "/var/lib/grafana"
grafana_config_dir: "/etc/grafana"
grafana_logs_dir: "/var/log/grafana"
grafana_plugins_dir: "/var/lib/grafana/plugins"
grafana_provisioning_dir: "/etc/grafana/provisioning"
grafana_pid_file_dir: "/var/run/grafana"

# Default dashboards to import
# Dans main.yml, modifiez la configuration des dashboards
grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 27
    datasource: "Prometheus-Local"
    title: "Node Exporter Full"

# UFW rules
# Dans main.yml, ajoutez ces règles UFW
grafana_ufw_rules:
  - port: "{{ grafana_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['application_hosts'][0]]['ansible_host'] }}"
  - port: "{{ prometheus_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['monitoring_hosts'][0]]['ansible_host'] }}"
  - port: "{{ prometheus_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['application_hosts'][0]]['ansible_host'] }}"
  - port: "{{ prometheus_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['bdd_hosts'][0]]['ansible_host'] }}"

# Performance tuning
grafana_max_open_files: 10000
grafana_max_concurrent_connections: 100

# Session management
grafana_session_provider: "file"
grafana_session_provider_config: "sessions"
grafana_cookie_secure: false
grafana_cookie_samesite: "lax"

# SMTP Configuration (optionnel)
grafana_smtp_enabled: false
grafana_smtp_host: "localhost:25"
grafana_smtp_user: ""
grafana_smtp_password: ""
grafana_smtp_from_address: ""

# Logging
grafana_log_mode: "console file"
grafana_log_level: "info"

# Metrics
grafana_metrics_enabled: true
grafana_metrics_basic_auth_username: "{{ grafana_admin_user }}"
grafana_metrics_interval: "10s"

# Default org preferences
grafana_default_theme: "dark"
grafana_default_timezone: "browser"