---
galaxy_info:
  author: Tistech0
  description: Role to install and configure Grafana
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - grafana
    - monitoring
    - dashboard