---
# Versions
prometheus_version: "2.30.3"
node_exporter_version: "1.3.1"

# Users and Groups
prometheus_user: "{{ lookup('env', 'PROMETHEUS_USER') | default('prometheus') }}"
prometheus_group: "prometheus"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"

# Paths
prometheus_config_path: /etc/prometheus
prometheus_data_path: /var/lib/prometheus
prometheus_binary_path: /usr/local/bin
prometheus_temp_path: /tmp/prometheus

# Network
prometheus_port: 9090
node_exporter_port: 9100
grafana_port: 3000

# Retention and Storage
prometheus_storage_retention_time: "15d"
prometheus_storage_retention_size: "50GB"

# Scrape configs
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

# Security
prometheus_web_external_url: "http://localhost:9090"
prometheus_web_route_prefix: "/"

# UFW rules en utilisant les groupes d'inventaire
prometheus_ufw_rules:
  - port: "{{ prometheus_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['monitoring_hosts'][0]]['ansible_host'] | default('any') }}"
  - port: "{{ node_exporter_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['monitoring_hosts'][0]]['ansible_host'] | default('any') }}"
  - port: "{{ grafana_port }}"
    proto: tcp
    from_ip: "{{ hostvars[groups['monitoring_hosts'][0]]['ansible_host'] | default('any') }}"

# Environment
prometheus_environment: "production"

# Node Exporter settings
node_exporter_listen_address: "0.0.0.0:{{ node_exporter_port }}"

# Additional security settings
prometheus_systemd_protect_system: "strict"
prometheus_systemd_protect_home: "yes"
prometheus_systemd_no_new_privileges: "yes"

# Additional metadata
prometheus_datacenter: "primary"
prometheus_environment_labels: {}

# Service limits
prometheus_service_nofile_limit: 65535
prometheus_service_nproc_limit: 1024
node_exporter_service_nofile_limit: 65535
node_exporter_service_nproc_limit: 1024