---
- hosts: bdd_hosts
  become: yes
  vars_files:
    - ../group_vars/all/vault.yml
  tasks:
    - name: Créer un conteneur MySQL avec une base de données par défaut
      community.docker.docker_container:
        name: mysql_container
        image: mysql:latest
        state: started
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "db_countersepitechapp"
        restart_policy: always
