---
- name: Restart Watchtower
  docker_container:
    name: "{{ watchtower_container_name }}"
    state: started
    restart: yes

- name: Restart Application
  docker_container:
    name: "{{ app_container_name }}"
    state: started
    restart: yes

- name: Reload Prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200
  register: prometheus_reload
  ignore_errors: yes
  when: 
    - enable_monitoring | default(false)
    - inventory_hostname in groups['monitoring_hosts']