---
- name: Ensure temporary directory exists
  file:
    path: "/tmp/prometheus"
    state: directory
    mode: '0755'

- name: Download and Install Node Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_binary_path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ prometheus_binary_path }}/node_exporter"

- name: Set Node Exporter binary permissions
  file:
    path: "{{ prometheus_binary_path }}/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'

- name: Clean up temporary directory
  file:
    path: "/tmp/prometheus"
    state: absent