---
# Watchtower configuration
watchtower_user: "{{ lookup('env', 'WATCHTOWER_USER') | default('watchtower') }}"
watchtower_interval: 30
watched_repo: "tistech0/countersepitechapp:latest"

# Docker configuration
watchtower_config_dir: /etc/watchtower
docker_socket: /var/run/docker.sock
docker_api_version: "1.41"

# Container configuration
watchtower_container_name: watchtower
watchtower_image: containrrr/watchtower:latest
watchtower_metrics_port: 8080

# Application container
app_container_name: "{{ watched_repo | regex_replace('^.*/', '') | regex_replace(':.*$', '') }}"
app_container_port: 80

# Watchtower settings
watchtower_cleanup: true
watchtower_include_stopped: false
watchtower_remove_volumes: false
watchtower_monitor_only: false
watchtower_log_level: "info"
watchtower_stop_timeout: "10s"

# Dependencies
dependencies:
  apt:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip
  pip:
    - docker
    - docker-compose

# Security
watchtower_ufw_rules:
  - port: "{{ watchtower_metrics_port }}"
    proto: tcp
    from_ip: "{{ groups['monitoring_hosts'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

# Docker security
docker_userns_remap: true
docker_network: "watchtower_network"

# Monitoring configuration
metrics_scrape_interval: "15s"
enable_monitoring: true

# Notification settings
notifications:
  slack:
    enabled: false
    hook_url: ""
    identifier: "watchtower"
  email:
    enabled: false
    server: ""
    from: ""
    to: ""

