name: mirror

on:
  push:
    branches: [main]

jobs:

   mirror:
    name: Push content of the current repo on mirror
    runs-on: ubuntu-latest
    needs: [sonarQube, build_api_image]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2025/T-CLO-901-NAN_10.git
          ssh_private_key: ${{ secrets.SSH_KEY }}
